name: Arm-dockerBuild
on:
  push:
    paths:
    - 'image/arm/**'
    - '.github/workflows/push-arm.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      VERSION: 2022.7.0-cloudflared22.7.0
      IMAGE_NAME: cloudflared-access-arm64
      TEAM: namagominetwork
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./image/arm
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.TEAM }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}