name: Arm-cloudflared-dockerBuild
on:
  push:
    paths:
    - 'image/arm/**'
    - '.github/workflows/push-arm.yml'

jobs:
  Arm-cloudflared-build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: cloudflared-access-arm64
      TEAM: namagominetwork
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # gitのcommit shaをtagにする
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./image/arm
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.TEAM }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}